# # Core Qdrant Configuration

# # Cluster settings (for distributed deployments)
# cluster:
#   # Enabled clustering (true/false)
#   enabled: false  # Usually false for single-node setups
#   # Other cluster settings (peer addresses, etc.) if enabled

# # Service settings
# service:
#   # GRPC port
#   grpc_port: 6333
#   # HTTP port
#   http_port: 6332
#   # Metrics port
#   metrics_port: 9900
#   # Enable CORS (Cross-Origin Resource Sharing) for web access
#   cors:
#     enabled: true
#     allowed_origins: ["*"] # Or specify specific origins
#   # Public API address (important for remote access)
#   public_api_address: "0.0.0.0" # Listen on all interfaces.  Use a specific IP if needed.
#   # Enable TLS for gRPC and HTTP
#   tls:
#     enabled: false # Set to true to enable TLS
#     cert_path: "" # Path to your certificate
#     key_path: "" # Path to your private key

# # Storage settings
# storage:
#   # Type of storage (in-memory or persistent)
#   type: "memmap" # "memmap" for memory-mapped files (fast, persistent), "rocksdb" for RocksDB (persistent)
#   # Directory for persistent storage (if applicable)
#   storage_path: "/qdrant/db" # Only needed if type is 'memmap' or 'rocksdb'
#   # WAL (Write-Ahead Log) configuration (for durability)
#   wal:
#     enabled: true # Enable the WAL for crash recovery

# # Optimizer settings (for vector search performance)
# optimizer:
#   # Number of points to trigger indexing
#   default_segment_number: 4
#   # Other optimizer settings (e.g., indexing thresholds) - consult Qdrant docs for advanced tuning

# # Quantization settings (for reducing memory usage)
# quantization:
#   # Type of quantization (e.g., product quantization)
#   type: "hnsw" # or "binary", "pt" (Product Quantization)
#   # ... other quantization parameters (depending on the type)

# # HNSW (Hierarchical Navigable Small World) index settings - Important for search speed
# hnsw_config:
#   ef_construct: 100 # Higher = better recall, slower indexing
#   ef: 16 # Higher = better recall, slower search
#   M: 16 # Number of connections per node in the graph

# # Payload storage settings (for storing associated data with vectors)
# payload_storage:
#   # Type of payload storage (usually "rocksdb")
#   type: "rocksdb"
#   # Path to the payload storage directory
#   payload_path: "/qdrant/payload"

# # Telemetry settings (for usage reporting)
# telemetry:
#   enabled: true # Consider disabling in production if you don't need it

# # Authentication settings (for securing your Qdrant instance)
# auth:
#   enabled: false # Set to true to enable authentication
#   jwt_secret: "your_secret_key" # Replace with a strong, randomly generated secret

# # Limits settings (for controlling resource usage)
# limits:
#   max_points_in_collection: 1000000 # Example limit - adjust as needed
#   # Other limits (e.g., payload size) - consult Qdrant documentation

# # Log settings
# logging:
#   level: "info" # "debug", "info", "warn", "error"

# # Snapshot settings (for backups)
# snapshots:
#   # Directory where snapshots are stored
#   snapshots_path: "/qdrant/snapshots"
#   # How often to create snapshots (e.g., every hour)
#   schedule: "0 0 * * *" # Example cron expression (daily at midnight)